
trigger:
- azure-pipelines

pool:
  vmImage: 'vs2017-win2016'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.11.2'    
  displayName: 'Install Node.js'

- script: npm install -g npm@6.0.1
  displayName: 'Install NPM'

- script: npm install -g gulp
  displayName: 'Install Gulp'

- script: npm install
  displayName: 'NPM install'

- script: gulp debug-no-start --win32
  displayName: 'Gulp debug-no-start'

- task: PublishPipelineArtifact@0
  inputs: 
    artifactName: betaflight-configurator
    targetPath: '$(System.DefaultWorkingDirectory)/debug/betaflight-configurator'
