
trigger:
- azure-pipelines

pool:
  vmImage: 'vs2017-win2016'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.11.2'    
  displayName: 'Install Node.js'

- script: npm install -g npm@6.0.1
  displayName: 'Install NPM'

- script: npm install -g gulp
  displayName: 'Install Gulp'

- script: npm install
  displayName: 'NPM install'

- script: gulp debug-no-start --win32
  displayName: 'Gulp debug-no-start'

# Testing direct download using different task
#- task: ArchiveFiles@2
#  inputs:
#    archiveFile: '$(Build.ArtifactStagingDirectory)/betaflight-configurator.zip'
#    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/debug'
#    includeRootFolder: false

- task: DownloadPipelineArtifact@0
  inputs: 
    targetPath: '$(System.DefaultWorkingDirectory)/debug'
